FROM registry.access.redhat.com/ubi9/nodejs-18:latest

WORKDIR /usr/src/app

RUN mkdir web

COPY Makefile Makefile
COPY web/package*.json ./web
RUN make install-frontend-ci-clean

COPY web/ /usr/src/app/web

RUN make build-frontend

ENTRYPOINT ["make", "test-frontend"]
